services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: migrate
      POSTGRES_PASSWORD: migrate
      POSTGRES_DB: migrate

workspace:
  base: /go
  path: src/github.com/shanna/migrate

pipeline:
  build:
    image: golang
    commands:
      - sleep 4 # Postgres can take a while to start. This just creates cleaner logs.
      - go get ./...
      - go test ./...
